# https://taskfile.dev

version: '3'

interval: 100ms

vars:
  GREETING: Hello, World!

tasks:
  default:
    sources:
      - "**/*.go"
    cmds:
      - cd ../.. && make "test^dg^step0"
    silent: true
